/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadingWatchListRouteImport } from './routes/reading-watch-list'
import { Route as IndexRouteImport } from './routes/index'

const ReadingWatchListRoute = ReadingWatchListRouteImport.update({
  id: '/reading-watch-list',
  path: '/reading-watch-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reading-watch-list': typeof ReadingWatchListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reading-watch-list': typeof ReadingWatchListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reading-watch-list': typeof ReadingWatchListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reading-watch-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reading-watch-list'
  id: '__root__' | '/' | '/reading-watch-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadingWatchListRoute: typeof ReadingWatchListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reading-watch-list': {
      id: '/reading-watch-list'
      path: '/reading-watch-list'
      fullPath: '/reading-watch-list'
      preLoaderRoute: typeof ReadingWatchListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadingWatchListRoute: ReadingWatchListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
